# Generated by Django 5.0.2 on 2026-02-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('place', models.CharField(max_length=160)),
                ('time_text', models.CharField(max_length=40)),
                ('event_name', models.CharField(default='India AI Summit', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120)),
                ('event_name', models.CharField(default='India AI Summit', max_length=120)),
                ('pitch_text', models.TextField()),
                ('pitch_audio_url', models.URLField(blank=True)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('tag', models.CharField(blank=True, max_length=80)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
